### Promise 错误处理
```
var promise = new Promise(function(resolve, reject) {
    resolve("ok");
    throw new Error('wtf')
    //setTimeout(function() { throw new Error('test') }, 0)
});
```
* 看不到任何报错
```
var promise = new Promise(function(resolve, reject) {
    resolve("ok");
    throw new Error('wtf')
    //setTimeout(function() { throw new Error('test') }, 0)
});
promise.then(function(value) { console.log(value) })
    .catch((err)=>{
        console.log(err)
    })
process.on('unhandledRejection', function (err, p) {
    console.error('catch exception:',err.stack)
});
```



参考文章：[Promise 吞掉报错信息的问题](https://adoyle.me/blog/silent-fail-in-promise.html)